"""Canonical Polymarket pre-trade reason codes."""

ALLOWANCE_OK = "ALLOWANCE_OK"
ALLOWANCE_LOOKUP_ERROR = "ALLOWANCE_LOOKUP_ERROR"
CLOB_ALLOWANCE_MISMATCH = "CLOB_ALLOWANCE_MISMATCH"
INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
MISSING_ALLOWANCE = "MISSING_ALLOWANCE"
